name: gox-clips-dev
services:
  app:
    build: 
      context: ../../
      dockerfile: docker/dev/dev.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../../:/app
    environment:
      - GO_ENV=development
      - APP_PORT=8080
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=gox-clips
